### PR TITLE
changed images to be relative and inside the repo

### PR DESCRIPTION
**Pull request by codingontheway**

### CODE REVIEW

**Comment by MohabMohie** [comment]
Kindly resolve the conflicts first. 🙏🏻

**Review by MohabMohie — CHANGES_REQUESTED** [review]
Kindly resolve the conflicts first 🙏🏻

**Comment by codingontheway** [comment]
Resolved 👍

**Comment by MohabMohie** [comment]
Thank you for your valued contributions 🙏🏻

**Pull request merged**
